{% set name = "docstrfmt" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/docstrfmt-{{ version }}.tar.gz
  sha256: e95f93ae1c4fe7b5bdb55eaaeaa8aaba862602a76a6aa7827b81ed52fc366d72

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - docstrfmt = docstrfmt.main:main
    - docstrfmtd = docstrfmt.server:main

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4,<4
    - pip
  run:
    - python >={{ python_min }}
    - black >=24
    - click >=8
    - coverage >=7.11
    - docutils >=0.21
    - libcst >=1
    - platformdirs >=4
    - roman
    - sphinx >=7
    - tabulate >=0.9
    - toml >=0.10
    - aiohttp >=3
    - types-docutils =0.22.3.20251115.*

test:
  imports:
    - docstrfmt
  commands:
    - pip check
    - docstrfmt --help
    - docstrfmtd --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: 'docstrfmt: A formatter for Sphinx flavored reStructuredText.'
  home: https://pypi.org/project/docstrfmt
  dev_url: https://github.com/LilSpazJoekp/docstrfmt
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - anjos
